backend:
  name: git-gateway
  branch: master

media_folder: static/cms-assets
public_folder: /assets

collections:
  - label: "Home"
    name: "home"
    folder: "content/home"
    create: false
    slug: "index"
    fields:
      - { label: Banner Image, name: banner, widget: image }
      - {
          label: "Introduction Title",
          name: "introduction-title",
          widget: "string",
        }
      - {
          label: Introduction Description,
          name: introduction-description,
          widget: string,
        }
      - label: Values
        name: values
        widget: list
        fields:
          - { label: Value Text, name: value, widget: string }
          - { label: Value Image, name: value-img, widget: image }
      - { label: Location Image, name: location-img, widget: image }
      - { label: Location Title, name: location-title, widget: string }
      - {
          label: Location Description,
          name: location-description,
          widget: string,
        }
      - { label: Booking Title, name: booking-title, widget: string }
      - { label: Instagram Name, name: instagram-name, widget: string }
      - label: Instagram Embed Links
        name: instagram-links
        widget: list
        fields:
          - { label: Embed Link, name: embed-link, widget: string }
      - label: Testimonials
        name: testimonials
        widget: list
        fields:
          - { label: Testimonial Text, name: testimonial-text, widget: string }
          - { label: Testimonial Name, name: testimonial-name, widget: string }
          - {
              label: Testimonial Occupation,
              name: testimonial-occupation,
              widget: string,
            }
  - label: "About"
    name: "about"
    create: false
    slug: "index"
    editor:
      preview: false
    fields:
      - { label: Banner Image, name: banner, widget: image }
    files:
      - label: "Staff"
        name: "staff"
        file: "content/about/staff.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Attitude & Ettiquette"
        name: "attitude-ettiquette"
        file: "content/about/attitude-ettiquette.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: Values
            name: values
            widget: list
            fields:
              - { label: Value, name: value, widget: string }
      - label: "Studios"
        name: "studios"
        file: "content/about/studios.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Studio
            name: studio
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Photo, name: photo, widget: image }
  - label: "Classes"
    name: "classes"
    folder: "content/classes"
    create: true
    fields:
      - { label: Class Name, name: title, widget: string }
      - { label: Class Age Group, name: subtitle, widget: string }
      - { label: Class Description, name: description, widget: markdown }
      - { label: Class Image, name: image, widget: image }
