backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin

media_folder: static/cms-assets
public_folder: /assets

collections:
  - label: "Home"
    name: "home"
    folder: "content/home"
    create: false
    editor:
      preview: false
    slug: "index"
    fields:
      - { label: Banner Image, name: banner, widget: image }
      - {
          label: "Show Notification Bar",
          name: "show-notification-bar",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Notification Bar Content",
          name: "notification-content",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Introduction Title",
          name: "introduction-title",
          widget: "string",
        }
      - {
          label: Introduction Description,
          name: introduction-description,
          widget: string,
        }
      - { label: Location Image, name: location-img, widget: image }
      - { label: Location Title, name: location-title, widget: string }
      - {
          label: Location Description,
          name: location-description,
          widget: string,
        }
      - { label: Booking Title, name: booking-title, widget: string }
      - { label: Instagram Name, name: instagram-name, widget: string }
      - label: Instagram Embed Links
        name: instagram-links
        widget: list
        fields:
          - { label: Embed Link, name: embed-link, widget: string }
      - label: Testimonials
        name: testimonials
        widget: list
        fields:
          - { label: Testimonial Text, name: testimonial-text, widget: string }
          - { label: Testimonial Name, name: testimonial-name, widget: string }
          - {
              label: Testimonial Occupation,
              name: testimonial-occupation,
              widget: string,
            }
  - label: "About"
    name: "about"
    create: false
    slug: "index"
    editor:
      preview: false
    files:
      - label: "Staff"
        name: "staff"
        file: "content/about/staff.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Photo, name: photo, widget: image }
      - label: "Attitude & Ettiquette"
        name: "attitude-ettiquette"
        file: "content/about/attitude-ettiquette.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: Values
            name: values
            widget: list
            fields:
              - { label: Value, name: value, widget: string }
      - label: "Studios"
        name: "studios"
        file: "content/about/studios.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Studio
            name: studio
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Photo, name: photo, widget: image }
      - label: "Create New Section"
        name: "new-sections"
        file: "content/about/new-sections.md"
        fields:
          - label: New Section
            name: section
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Background Colour, name: bg-color, widget: string }
              - { label: Content, name: content, widget: markdown }
  - label: "Classes"
    name: "classes"
    folder: "content/classes"
    editor:
      preview: false
    create: true
    fields:
      - {
          label: "Order",
          name: "order",
          widget: "select",
          options: ["1", "2", "3", "4", "5", "6", "7", "8"],
        }
      - { label: Class Name, name: title, widget: string }
      - { label: Class Location, name: subtitle, widget: string }
      - { label: Class Description, name: description, widget: markdown }
      - { label: Class Image, name: image, widget: image }
      - label: Class Times
        name: class-times
        widget: list
        fields:
          - {
              label: Day,
              name: day,
              widget: select,
              options:
                [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                  "Sunday",
                ],
            }
          - {
              label: Start Time,
              name: start-time,
              widget: datetime,
              default: "",
              format: "hh:mm A",
              dateFormat: false,
              timeFormat: "hh:mm A",
            }
          - {
              label: End Time,
              name: end-time,
              widget: datetime,
              default: "",
              format: "hh:mm A",
              dateFormat: false,
              timeFormat: "hh:mm A",
            }
  - label: "Term Dates"
    name: "term-dates"
    slug: "index"
    folder: "content/term-dates"
    editor:
      preview: false
    create: false
    summary: "Enter Term Dates"
    fields:
      - label: Term 1
        name: term-one
        widget: list
        allow_add: false
        fields:
          - {
              label: Start Date,
              name: start-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
          - {
              label: End Date,
              name: end-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
      - label: Term 2
        name: term-two
        widget: list
        allow_add: false
        fields:
          - {
              label: Start Date,
              name: start-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
          - {
              label: End Date,
              name: end-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
      - label: Term 3
        name: term-three
        widget: list
        allow_add: false
        fields:
          - {
              label: Start Date,
              name: start-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
          - {
              label: End Date,
              name: end-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
      - label: Term 4
        name: term-four
        widget: list
        allow_add: false
        fields:
          - {
              label: Start Date,
              name: start-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
          - {
              label: End Date,
              name: end-date,
              widget: datetime,
              format: "D MMMM",
              dateFormat: "D MMMM",
              timeFormat: false,
            }
  - label: "Banner Images"
    name: "banner-images"
    summary: "Select Banner Images"
    slug: "index"
    folder: "content/banner-images"
    editor:
      preview: false
    create: false
    fields:
      - { label: About, name: about-banner-img, widget: image }
      - { label: Classes, name: classes-banner-img, widget: image }
      - { label: Timetable, name: timetable-banner-img, widget: image }
      - { label: Information, name: information-banner-img, widget: image }
      - { label: Contact, name: contact-banner-img, widget: image }
      - { label: Sign Up, name: signup-banner-img, widget: image }
  - label: "Information"
    name: "information"
    create: false
    slug: "index"
    editor:
      preview: false
    files:
      - label: "Uniform"
        name: "uniform"
        file: "content/information/uniform.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Uniform Card
            name: uniform-card
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Photo, name: photo, widget: image }
      - label: "Terms and Conditions"
        name: "terms-and-conditions"
        file: "content/information/terms-and-conditions.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Terms and Conditions, name: content, widget: markdown }
