backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Homepage"
    name: "home"
    folder: "content/home"
    create: false
    slug: "home"
    path: "{{title}}/home"
    editor:
      preview: true
    fields:
      - { label: Banner Image, name: banner, widget: image }
      - {
          label: "Introduction Title",
          name: "introduction-title",
          widget: "string",
        }
      - {
          label: Introduction Description,
          name: introduction-description,
          widget: string,
        }
      - label: Values
        name: values
        widget: list
        fields:
          - { label: Value Text, name: value, widget: string }
          - { label: Value Image, name: value-img, widget: image }
      - { label: Location Image, name: location-img, widget: image }
      - { label: Location Title, name: location-title, widget: string }
      - {
          label: Location Description,
          name: location-description,
          widget: string,
        }
      - label: Classes
        name: classes
        widget: list
        fields:
          - { label: Class Name, name: class-name, widget: string }
          - {
              label: Class Description,
              name: class-description,
              widget: string,
            }
          - { label: Class Image, name: class-img, widget: image }
      - { label: Instagram Name, name: instagram-name, widget: string }
      - label: Instagram Embed Links
        name: instagram-links
        widget: list
        fields:
          - { label: Embed Link, name: embed-link, widget: string }
      - label: Testimonials
        name: testimonials
        widget: list
        fields:
          - { label: Testimonial Text, name: testimonial-text, widget: string }
          - { label: Testimonial Name, name: testimonial-name, widget: string }
          - {
              label: Testimonial Occupation,
              name: testimonial-occupation,
              widget: string,
            }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }
